version: "3"

services:
  db:
    image:mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: energy_report_consumption
    ports:
    - 3306:3306
  web:
    build: ./api
    command: python api/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/webproject
    ports:
      - 8000:8000
    depends_on:
      - db
