# Generated by Django 3.0.4 on 2020-03-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapplication', '0002_auto_20200311_1019'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
